CREATE TABLE IF NOT EXISTS person_profiles (
  person_id INT NOT NULL PRIMARY KEY,
  last_name VARCHAR(80) NULL,
  first_name VARCHAR(80) NULL,
  relation_label VARCHAR(80) NULL,
  memo TEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
